console.log("           _                         _")
console.log("       _==/          i     i          \\==_")
console.log("     /XX/            |\\___/|            \\XX\\")
console.log("   /XXXX\\            |XXXXX|            /XXXX\\")
console.log("  /XXXXXX\\_         _XXXXXXX_         _/XXXXXX\\")
console.log(" XXXXXXXXXXXxxxxxxxXXXXXXXXXXXxxxxxxxXXXXXXXXXXX")
console.log("|XXXX \x1b[36mShiro_dev\x1b[0m XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|")
console.log("XXXXX https://github.com/adrims08 XXXXXXXXXXXXXXX")
console.log("|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|")
console.log(" XXXXXX/     \\XXXXXXXXXXXXXXXXXXXXX/     \\XXXXXX")
console.log("  \\XXX|       \\XXX/  \\XXXXX/  \\XXX/       |XXX/")
console.log("    \\XX\\       \\X/    \\XXX/    \\X/       /XX/")
console.log("       \"\\       \"      \\X/      \"       /\"")
console.log("                        !⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")

console.log("What are you doing \x1b[31mhere\x1b[0m!?")
console.log("\x1b[31mNo\x1b[0m! Don't answer me, just leave. NOW!!")